# Generated by Django 5.0 on 2023-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('item_desc', models.CharField(max_length=100)),
                ('item_price', models.IntegerField()),
                ('item_img', models.CharField(default='https://cdn-icons-png.flaticon.com/512/1147/1147805.png', max_length=1000)),
            ],
        ),
    ]
